In [121]:
import numpy as np

"""Axis = 0 means column wise , Axis = 1 means row wise"""

'Axis = 0 means column wise , Axis = 1 means row wise'

In [122]:
#Creating Numpy Array

my_list = [1,2,3,4]
np_array = np.array(my_list)

print("Converted Numpy List = ", np_array)

Converted Numpy List =  [1 2 3 4]


In [123]:
# Creating Numpy Matrix

mat= [[1,2,3] , [4,5,6], [7,8,9]]
np_mat= np.array(mat)

print("Converted Numpy matrix =\n" , np_mat)

Converted Numpy matrix =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### <u> Arange </u>

In [124]:
# Returns evenly spaced values within a given interval 
# with step size at 3rd position.
# Does not include stop Value

print("Values 0 to 9 = ",np.arange(0,10))

print("Even values from 1 - 10 = ",np.arange(0,11,2))

Values 0 to 9 =  [0 1 2 3 4 5 6 7 8 9]
Even values from 1 - 10 =  [ 0  2  4  6  8 10]


### <u> Linspace </u>

In [125]:
# Returns evenly spaced values within a given interval
# with No of values at 3rd position

print("20 values within range (0,10) --> \n", np.linspace(0,10,20))

20 values within range (0,10) --> 
 [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


###### <font color= green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

### <u> Zeros and Ones </u>

In [126]:
# Generate arrays of Zeros

print("1D- Array of Zeros of length 3 = ",np.zeros(3))

print("5x5 Array of Zeros = \n", np.zeros((5,5)))

1D- Array of Zeros of length 3 =  [0. 0. 0.]
5x5 Array of Zeros = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [127]:
# Generate arrays of Ones

print("1-D array of size =3 --> ",np.ones(3))

print("3x3 Array of Ones = \n",np.zeros((3,3)))

1-D array of size =3 -->  [1. 1. 1.]
3x3 Array of Ones = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### <u> Eye </u>

In [128]:
# Creates an identity Matrix

print("Identity matrix of 4 dim = \n",np.eye(4))

Identity matrix of 4 dim = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### <u> Random </u>

##### 1. rand

In [129]:
# Creates an array of the given shape and 
# populates it with random samples from a UNIFORM DISTRIBUTION over (0,1)

print("print 2 random values (0,1) --> ",np.random.rand(2))

print("print 5x5 dim where random no's \
 belong to uniform distribution-> \n",np.random.rand(5,5))

print 2 random values (0,1) -->  [0.61380299 0.09511545]
print 5x5 dim where random no's  belong to uniform distribution-> 
 [[0.93344111 0.80935352 0.8535058  0.50811822 0.91168907]
 [0.06197523 0.11142186 0.16802457 0.57008286 0.98848438]
 [0.19941129 0.67758617 0.74264794 0.92552897 0.20094175]
 [0.69704696 0.54383621 0.9032017  0.52536887 0.41287334]
 [0.98799384 0.82943196 0.55777227 0.32964587 0.68316744]]


##### 2. randn

In [130]:
# Returns a Sample from the 
# "STD. NORMAL" distribution [mean =0 , std Dev =1]

# Unlike "rand" which is uniform, 
# values closer to zero are more likely to appear.

print("print 2 random values --> ",np.random.randn(2))

print("print 5x5 dim where random no's \
 belong to STD. NORMAL distribution -> \n",np.random.randn(5,5))


print 2 random values -->  [-0.06172514 -0.22676518]
print 5x5 dim where random no's  belong to STD. NORMAL distribution -> 
 [[ 1.88108008  0.8295548  -0.23536495 -0.10098635 -1.63952666]
 [ 1.57161429  0.85097638  1.03429037 -0.65417468 -0.94809436]
 [-0.24991788 -0.59235928  1.74143021 -0.6641156   1.01126207]
 [-1.13721523  0.55618297  0.92798696  1.06684118 -0.73469427]
 [-0.94790321  0.40506257 -0.82784381 -0.16104503  0.50155866]]


##### 3. randint

In [131]:
# Returns random integers in (a,b] 
# where a= included to b= exclusive

print("Generate rand no in range (1,100)= ", np.random.randint(1,100))

print("Generate 10 random no's in range (1,100) = ",np.random.randint(1,100,10))

Generate rand no in range (1,100)=  2
Generate 10 random no's in range (1,100) =  [ 2  1 26 35 62 38 93 95 48 86]


### <u> Working on Array </u>

In [132]:
# Toy data

arr=np.arange(20)
rand_arr = np.random.randint(0,50,10)

print("arr = ",arr)
print("rand_arr = \n",rand_arr)

arr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
rand_arr = 
 [17  1  5 36 38  4 36  9  2  7]


1. Shape

In [133]:
# retuns the dimension of the numpy array

print("Size of the arr= ", arr.shape)
print("Sze of the rand_arr = ",rand_arr.shape)

# When only one is written then it means it is a 1D series

Size of the arr=  (20,)
Sze of the rand_arr =  (10,)


2. Reshape

In [134]:
# Returns an array containing the same data with a new shape

print(" convert arr  to 4x5 matrix =\n", arr.reshape(4,5))

 convert arr  to 4x5 matrix =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


3. MAX & MIN

In [135]:
temp = rand_arr.reshape(2,5)
print("temp = \n",temp)

print("\nminimum values along COLUMNS(axis=0) =\n ",temp.min(axis=0))
print("\nminimum values along ROWS(axis=1) =\n ",temp.min(axis=1))

temp = 
 [[17  1  5 36 38]
 [ 4 36  9  2  7]]

minimum values along COLUMNS(axis=0) =
  [4 1 5 2 7]

minimum values along ROWS(axis=1) =
  [1 2]


In [136]:
print("\nMAX values along COLUMNS(axis=0) =\n ",temp.max(axis=0))
print("\nMAX values along ROWS(axis=1) =\n ",temp.max(axis=1))


MAX values along COLUMNS(axis=0) =
  [17 36  9 36 38]

MAX values along ROWS(axis=1) =
  [38 36]


4. argmax, argmin

In [137]:
#Returns the indices of the maximum/minimum values along an axis.

print("\nPosition of MAX values along COLUMNS(axis=0) =\n ",temp.argmax(axis=0))
print("\nPosition of MAX values along ROWS(axis=1) =\n ",temp.argmax(axis=1))

print("\nPosition of MIN values along COLUMNS(axis=0) =\n ",temp.argmin(axis=0))
print("\nPosition of MIN values along ROWS(axis=1) =\n ",temp.argmin(axis=1))


Position of MAX values along COLUMNS(axis=0) =
  [0 1 1 0 0]

Position of MAX values along ROWS(axis=1) =
  [4 1]

Position of MIN values along COLUMNS(axis=0) =
  [1 0 0 1 1]

Position of MIN values along ROWS(axis=1) =
  [1 3]


### <u> NumPy Indexing and Selection </u>

In [138]:
# Toy data

arr=np.arange(20)
rand_arr = np.random.randint(0,50,10)

print("arr = ",arr)
print("rand_arr = \n",rand_arr)

arr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
rand_arr = 
 [ 5  1 38  9 41 34  6 31  4 40]


In [139]:
# INDEXING
print("Value at index 8= ",arr[8])

print("values in index range(2,5) = ",rand_arr[2:5])

Value at index 8=  8
values in index range(2,5) =  [38  9 41]


##### Memory Matters (IMP)

In [140]:
print("Original rand_arr = ", rand_arr)

temp = rand_arr
temp[0]= -1

print("temp = ",temp )
print("Original rand_arr = ", rand_arr)

Original rand_arr =  [ 5  1 38  9 41 34  6 31  4 40]
temp =  [-1  1 38  9 41 34  6 31  4 40]
Original rand_arr =  [-1  1 38  9 41 34  6 31  4 40]


###### <font color= green> Now note the changes also occur in our original array! Data is not copied, it's a view of the original array! This avoids memory problems!</font>

### Broadcasting

###### NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. 

###### That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list.

###### With NumPy arrays, you can broadcast a single value across a larger set of values:

In [141]:
#Setting a value with index range (Broadcasting)
print("Original rand_arr = ", rand_arr)

rand_arr[0:5]=100

print("Modified rand_arr = ", rand_arr)

Original rand_arr =  [-1  1 38  9 41 34  6 31  4 40]
Modified rand_arr =  [100 100 100 100 100  34   6  31   4  40]


In [142]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

##### Indexing a 2D array (matrices)

In [143]:
# The general format is arr_2d[row][col] or arr_2d[row,col] (RECOMMENDED)

In [144]:
arr_2d= np.arange(5,101,5).reshape(4,5)
print("3x3 Matrix =\n" ,arr_2d)

3x3 Matrix =
 [[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]]


In [145]:
# Getting individual element value

print("value at 1,0 position= ",arr_2d[1][0])
print("value at 1,1 position= ",arr_2d[1,1])

value at 1,0 position=  30
value at 1,1 position=  35


In [146]:
# 2D array slicing(IMP)

#row =0,1 & Col = 1...n
print("2d ex-\n" , arr_2d[:3,1:])

"""(IMP) Notice how this is different from this"""

print("\n2d ex- arr_2d[:3]= \n" , arr_2d[:3])
print("\n2d ex- arr_2d[:3][1]= \n" , arr_2d[:3][1])

#IT IS PRINTING THE LIST AT 1ST INDEX OF THE arr_2d[:3] """

print("\n2d ex- arr_2d[:3][1:]= \n" , arr_2d[:3][1:])

#IT IS PRINTING all the LIST after INDEX=1 OF THE arr_2d[:3] """



2d ex-
 [[10 15 20 25]
 [35 40 45 50]
 [60 65 70 75]]

2d ex- arr_2d[:3]= 
 [[ 5 10 15 20 25]
 [30 35 40 45 50]
 [55 60 65 70 75]]

2d ex- arr_2d[:3][1]= 
 [30 35 40 45 50]

2d ex- arr_2d[:3][1:]= 
 [[30 35 40 45 50]
 [55 60 65 70 75]]
