In [21]:
import numpy as np

# It's perhaps simplest to remember it as 0=down and 1=across.

# This means:
# Use axis=0 to apply a method down each column, or to the row labels (the index).
# Use axis=1 to apply a method across each row, or to the column labels.

 A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).

In [3]:
#Creating Numpy Array

my_list = [1,2,3,4]
np_array = np.array(my_list)

print("Converted Numpy List = ", np_array)

Converted Numpy List =  [1 2 3 4]


In [4]:
# Creating Numpy Matrix

mat= [[1,2,3] , [4,5,6], [7,8,9]]
np_mat= np.array(mat)

print("Converted Numpy matrix =\n" , np_mat)

Converted Numpy matrix =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### <u> Arange </u>

In [5]:
# Returns evenly spaced values within a given interval 
# with step size at 3rd position.
# Does not include stop Value

print("Values 0 to 9 = ",np.arange(0,10))

print("Even values from 1 - 10 = ",np.arange(0,11,2))

Values 0 to 9 =  [0 1 2 3 4 5 6 7 8 9]
Even values from 1 - 10 =  [ 0  2  4  6  8 10]


### <u> Linspace </u>

In [6]:
# Returns evenly spaced values within a given interval
# with No of values at 3rd position

print("20 values within range (0,10) --> \n", np.linspace(0,10,20))

20 values within range (0,10) --> 
 [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


###### <font color= green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

### <u> Zeros and Ones </u>

In [7]:
# Generate arrays of Zeros

print("1D- Array of Zeros of length 3 = ",np.zeros(3))

print("5x5 Array of Zeros = \n", np.zeros((5,5)))

1D- Array of Zeros of length 3 =  [0. 0. 0.]
5x5 Array of Zeros = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# Generate arrays of Ones

print("1-D array of size =3 --> ",np.ones(3))

print("3x3 Array of Ones = \n",np.zeros((3,3)))

1-D array of size =3 -->  [1. 1. 1.]
3x3 Array of Ones = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### <u> Eye </u>

In [9]:
# Creates an identity Matrix

print("Identity matrix of 4 dim = \n",np.eye(4))

Identity matrix of 4 dim = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### <u> Random </u>

##### 1. rand

In [10]:
# Creates an array of the given shape and 
# populates it with random samples from a UNIFORM DISTRIBUTION over (0,1)

print("print 2 random values (0,1) --> ",np.random.rand(2))

print("print 5x5 dim where random no's \
 belong to uniform distribution-> \n",np.random.rand(5,5))

print 2 random values (0,1) -->  [0.3215122  0.19867219]
print 5x5 dim where random no's  belong to uniform distribution-> 
 [[0.83150396 0.38691823 0.73204882 0.7536713  0.65973508]
 [0.72571231 0.16288487 0.41661096 0.24729888 0.42761901]
 [0.76831477 0.26679522 0.79691319 0.96037463 0.40272948]
 [0.2027657  0.7413382  0.43536894 0.87219934 0.69323522]
 [0.99147934 0.03272632 0.52150596 0.38900558 0.11988064]]


##### 2. randn

In [11]:
# Returns a Sample from the 
# "STD. NORMAL" distribution [mean =0 , std Dev =1]

# Unlike "rand" which is uniform, 
# values closer to zero are more likely to appear.

print("print 2 random values --> ",np.random.randn(2))

print("print 5x5 dim where random no's \
 belong to STD. NORMAL distribution -> \n",np.random.randn(5,5))


print 2 random values -->  [0.17162702 0.82272502]
print 5x5 dim where random no's  belong to STD. NORMAL distribution -> 
 [[-1.48476287e+00  1.20543451e+00  5.49974667e-01  7.27782938e-01
   8.43113284e-02]
 [-1.10881328e+00  1.16254084e+00 -2.57080545e-01 -5.56907834e-01
  -8.83031727e-01]
 [ 2.12208457e+00  1.67763683e-01  1.31937183e+00 -2.93260553e+00
   4.74109535e-01]
 [-6.74875540e-01  3.25532217e-02  5.40284808e-01  1.43183352e-01
   1.14348786e+00]
 [-7.18542538e-01  1.04597441e+00 -1.93671166e-03  3.75061986e-01
   3.65862150e-01]]


##### 3. randint

In [12]:
# Returns random integers in (a,b] 
# where a= included to b= exclusive

print("Generate rand no in range (1,100)= ", np.random.randint(1,100))

print("Generate 10 random no's in range (1,100) = ",np.random.randint(1,100,10))

Generate rand no in range (1,100)=  93
Generate 10 random no's in range (1,100) =  [61 37 47 31 87 41 12  7 90 98]


### <u> Working on Array </u>

In [13]:
# Toy data

arr=np.arange(20)
rand_arr = np.random.randint(0,50,10)

print("arr = ",arr)
print("rand_arr = \n",rand_arr)

arr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
rand_arr = 
 [14 48 42 26 39 41 20  9 43 37]


1. Shape

In [14]:
# retuns the dimension of the numpy array

print("Size of the arr= ", arr.shape)
print("Sze of the rand_arr = ",rand_arr.shape)

# When only one is written then it means it is a 1D series

Size of the arr=  (20,)
Sze of the rand_arr =  (10,)


2. Reshape

In [17]:
# Returns an array containing the same data with a new shape

print(" convert arr  to 4x5 matrix =\n", arr.reshape(4,5))

 convert arr  to 4x5 matrix =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


3. MIN & MAX

In [18]:
temp = rand_arr.reshape(2,5)
print("temp = \n",temp)

print("\nminimum values along COLUMNS(axis=0) =\n ",temp.min(axis=0))
print("\nminimum values along ROWS(axis=1) =\n ",temp.min(axis=1))

temp = 
 [[14 48 42 26 39]
 [41 20  9 43 37]]

minimum values along COLUMNS(axis=0) =
  [14 20  9 26 37]

minimum values along ROWS(axis=1) =
  [14  9]


In [136]:
print("\nMAX values along COLUMNS(axis=0) =\n ",temp.max(axis=0))
print("\nMAX values along ROWS(axis=1) =\n ",temp.max(axis=1))


MAX values along COLUMNS(axis=0) =
  [17 36  9 36 38]

MAX values along ROWS(axis=1) =
  [38 36]


4. argmax, argmin

In [137]:
#Returns the indices of the maximum/minimum values along an axis.

print("\nPosition of MAX values along COLUMNS(axis=0) =\n ",temp.argmax(axis=0))
print("\nPosition of MAX values along ROWS(axis=1) =\n ",temp.argmax(axis=1))

print("\nPosition of MIN values along COLUMNS(axis=0) =\n ",temp.argmin(axis=0))
print("\nPosition of MIN values along ROWS(axis=1) =\n ",temp.argmin(axis=1))


Position of MAX values along COLUMNS(axis=0) =
  [0 1 1 0 0]

Position of MAX values along ROWS(axis=1) =
  [4 1]

Position of MIN values along COLUMNS(axis=0) =
  [1 0 0 1 1]

Position of MIN values along ROWS(axis=1) =
  [1 3]


### <u> NumPy Indexing and Selection </u>

In [138]:
# Toy data

arr=np.arange(20)
rand_arr = np.random.randint(0,50,10)

print("arr = ",arr)
print("rand_arr = \n",rand_arr)

arr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
rand_arr = 
 [ 5  1 38  9 41 34  6 31  4 40]


In [139]:
# INDEXING
print("Value at index 8= ",arr[8])

print("values in index range(2,5) = ",rand_arr[2:5])

Value at index 8=  8
values in index range(2,5) =  [38  9 41]


##### Memory Matters (IMP)

In [140]:
print("Original rand_arr = ", rand_arr)

temp = rand_arr
temp[0]= -1

print("temp = ",temp )
print("Original rand_arr = ", rand_arr)

Original rand_arr =  [ 5  1 38  9 41 34  6 31  4 40]
temp =  [-1  1 38  9 41 34  6 31  4 40]
Original rand_arr =  [-1  1 38  9 41 34  6 31  4 40]


###### <font color= green> Now note the changes also occur in our original array! Data is not copied, it's a view of the original array! This avoids memory problems!</font>

### Broadcasting

###### NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. 

###### That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list.

###### With NumPy arrays, you can broadcast a single value across a larger set of values:

In [141]:
#Setting a value with index range (Broadcasting)
print("Original rand_arr = ", rand_arr)

rand_arr[0:5]=100

print("Modified rand_arr = ", rand_arr)

Original rand_arr =  [-1  1 38  9 41 34  6 31  4 40]
Modified rand_arr =  [100 100 100 100 100  34   6  31   4  40]


In [142]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

##### Indexing a 2D array (matrices)

In [143]:
# The general format is arr_2d[row][col] or arr_2d[row,col] (RECOMMENDED)

In [144]:
arr_2d= np.arange(5,101,5).reshape(4,5)
print("3x3 Matrix =\n" ,arr_2d)

3x3 Matrix =
 [[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]]


In [145]:
# Getting individual element value

print("value at 1,0 position= ",arr_2d[1][0])
print("value at 1,1 position= ",arr_2d[1,1])

value at 1,0 position=  30
value at 1,1 position=  35


In [146]:
# 2D array slicing(IMP)

#row =0,1 & Col = 1...n
print("2d ex-\n" , arr_2d[:3,1:])

"""(IMP) Notice how this is different from this"""

print("\n2d ex- arr_2d[:3]= \n" , arr_2d[:3])
print("\n2d ex- arr_2d[:3][1]= \n" , arr_2d[:3][1])

#IT IS PRINTING THE LIST AT 1ST INDEX OF THE arr_2d[:3] """

print("\n2d ex- arr_2d[:3][1:]= \n" , arr_2d[:3][1:])

#IT IS PRINTING all the LIST after INDEX=1 OF THE arr_2d[:3] """



2d ex-
 [[10 15 20 25]
 [35 40 45 50]
 [60 65 70 75]]

2d ex- arr_2d[:3]= 
 [[ 5 10 15 20 25]
 [30 35 40 45 50]
 [55 60 65 70 75]]

2d ex- arr_2d[:3][1]= 
 [30 35 40 45 50]

2d ex- arr_2d[:3][1:]= 
 [[30 35 40 45 50]
 [55 60 65 70 75]]
